title: ☞ Digital Archaeology
description: Introduction to Digital Archaeology. Also known as CLCV 3000 A and DIGH 3700 B.
theme: just-the-docs

url: https://shawngraham.github.io/hist3000-f26

aux_links:
  Carleton University: https://carleton.ca
  Shawn Graham: https://shawngraham.github.io

heading_anchors: true

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: NB!
    color: blue
